### ISSUE TITLE
如需换友链请在此留言

### ISSUE THREAD

**Issue by Mr-houzi** [Mr-houzi/Mr-houzi.github.io#1]
技术交流博客，如需换友链请在此留言！

**格式**

```
猴子星球: 
    link: https://mr-houzi.com
    avatar: http://oz57h7yc0.bkt.clouddn.com/assets/images/avatar.png
    descr: "最不务正业的程序猿"
```

【link】：博客地址
【avatar】：头像
【descr】：博客描述（建议15字内）

**Comment by yuyedaidao** [comment]
来来来，加友链
```
WangYQ:
    link: http://mooncake.wang
    avatar: https://avatars.githubusercontent.com/u/6354958?v=4
    descr: "干脆不排版了"
```
格式没看懂
